version: 2

models:
  - name: stg_ga4_events
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - not_null

  - name: mart_attribution_first_click
    columns:
      - name: user_id
        tests:
          - not_null
          - unique

  - name: mart_attribution_last_click
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
